import json
import os
from datetime import datetime, timedelta

import matplotlib.dates as mdates
import matplotlib.pyplot as plt
import networkx as nx
import numpy as np
import pandas as pd
import scipy.stats as stats
import tqdm.auto as tqdm
import yaml
from matplotlib.lines import Line2D
from matplotlib.patches import FancyArrowPatch


def load_logistics_data_from_excel(file_path: str,
                                   sheet_name: str = 'Route data',
                                   index_col: int = None,
                                   columns_to_read: str = 'A:J',
                                   skiprows: int = 3) -> pd.DataFrame:
    """Load logistics data from an Excel file."""
    if not os.path.exists(file_path):
        raise FileNotFoundError(f"The file {file_path} does not exist.")
    try:
        df = pd.read_excel(file_path, sheet_name=sheet_name, index_col=index_col,
                           usecols=columns_to_read, skiprows=skiprows)
        # df['Date'] = pd.to_datetime(df['Date'], errors='coerce')
        # df.dropna(subset=['Order ID', 'Product', 'Quantity', 'Price', 'Date'], inplace=True)
        return df
    except Exception as e:
        raise ValueError(
            f"An error occurred while reading the Excel file: {e}")


def clean_data(timetable_df: pd.DataFrame) -> pd.DataFrame:
    """
    generated by Data Wrangler.
    """
    # Filter rows based on column: 'Mode'
    timetable_df = timetable_df[(timetable_df['Mode'] == "NHSBT") | 
                                (timetable_df['Mode'] == "BMV") |
                                (timetable_df['Mode'] == "TNT")]
    # Drop rows with missing data in columns: 'Depart', 'Arrive', 'Frequency'
    timetable_df = timetable_df.dropna(
        subset=['Depart', 'Arrive', 'Frequency'])
    # Replace Mon-Fri values in the 'Frequency' column
    timetable_df['Frequency'] = timetable_df['Frequency'].replace({
        "Mon toFri": "Mon to Fri",
        "Mon-Fri": "Mon to Fri",
    })
    # Expand the values in 'Frequency' column into list of days
    timetable_df['Frequency'] = timetable_df['Frequency'].replace({
        "Mon to Fri": "Monday,Tuesday,Wednesday,Thursday,Friday",
        "Daily": "Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday",
        "Sat/Sun": "Saturday,Sunday",
        "Mon,Tue,Thur": "Monday,Tuesday,Thursday",
        "Mon,Tue,Thurs": "Monday,Tuesday,Thursday",
        "Tue to Sat": "Tuesday,Wednesday,Thursday,Friday,Saturday",
        "Sun/Mon": "Sunday,Monday",
        "Mon-Sat": "Monday,Tuesday,Wednesday,Thursday,Friday,Saturday",
    })
    # Split 'Frequency' column into individual days in a new column and explode them into new rows
    timetable_df['Day'] = timetable_df['Frequency'].str.split(',')
    timetable_df = timetable_df.explode('Day')
    # Filter rows based on column: 'Prime'
    timetable_df = timetable_df[~((timetable_df['Prime'] == "Samples,Dry shippers,I,Liverpool sesion") |
                                  (timetable_df['Prime'] == "Clin Coll") |
                                  (timetable_df['Prime'] == "Testing") |
                                  (timetable_df['Prime'] == "Testing, Cord Blood") |
                                  (timetable_df['Prime'] == "Cord Blood") |
                                  (timetable_df['Prime'] == "RCI") |
                                  (timetable_df['Prime'] == "Warehousing") |
                                  (timetable_df['Prime'] == "Empties return leg") |
                                  (timetable_df['Prime'] == "Consumables") |
                                  (timetable_df['Prime'] == "Warehouse") |
                                  (timetable_df['Prime'] == "Samples Run"))]
    return timetable_df


def shift_day(day):
    if day == 'Monday':
        return 'Tuesday'
    elif day == 'Tuesday':
        return 'Wednesday'
    elif day == 'Wednesday':
        return 'Thursday'
    elif day == 'Thursday':
        return 'Friday'
    elif day == 'Friday':
        return 'Saturday'
    elif day == 'Saturday':
        return 'Sunday'
    elif day == 'Sunday':
        return 'Monday'
    else:
        return day


def create_blood_matching_events(locations: pd.Series | list,
                                 matching_time: str = '08:00:00',
                                 buffer_time: str = '00:00:00',
                                 day_order: list[str] = None) -> pd.DataFrame:
    if day_order is None:
        day_order = ['Monday', 'Tuesday', 'Wednesday',
                     'Thursday', 'Friday', 'Saturday', 'Sunday']
    matching_dt = datetime.strptime(matching_time, "%H:%M:%S")
    buffer_td = timedelta(
        hours=int(buffer_time.split(":")[0]),
        minutes=int(buffer_time.split(":")[1]),
        seconds=int(buffer_time.split(":")[2])
    )
    constant_dt = matching_dt + buffer_td
    constant_time = constant_dt.time()
    # Create all combinations
    event_chronology = pd.DataFrame(
        [(loc, day, constant_time) for loc in locations for day in day_order],
        columns=['Location', 'Day', 'Event Time']
    )
    event_chronology['Event Type'] = 'Blood Matching'
    return event_chronology


def all_events_by_location(events_combined: pd.DataFrame,
                           day_order: list[str] = None) -> pd.DataFrame:
    """
    Combine all events sorted by location, with the earliest event first.
    Calculate the time to the next event for each location in minutes.
    """
    all_events = events_combined.sort_values(['Location', 'Day', 'Event Time'], ascending=[
                                             True, True, True]).reset_index(drop=True)
    if day_order is None:
        day_order = ['Monday', 'Tuesday', 'Wednesday',
                     'Thursday', 'Friday', 'Saturday', 'Sunday']
    # Map days to timedeltas
    day_to_timedelta = {day: pd.Timedelta(
        days=i) for i, day in enumerate(day_order)}
    all_events['Day_timedelta'] = all_events['Day'].map(day_to_timedelta)

    # Convert 'Event Time' to datetime (using dummy date)
    all_events['Event_dt'] = pd.to_datetime(
        all_events['Event Time'], format='%H:%M:%S')

    # Calculate day differences between adjacent rows
    all_events['Day_timedelta'] = pd.to_timedelta(all_events['Day_timedelta'])
    all_events['day_diffs'] = all_events['Day_timedelta'].diff().fillna(
        pd.Timedelta(0))

    # Calculate time differences between adjacent rows
    all_events['time_diffs'] = all_events['Event_dt'].diff().fillna(
        pd.Timedelta(0))

    # Add day_diffs to time_diffs to get total time to next event
    all_events['Time from Previous'] = (
        all_events['time_diffs'] + all_events['day_diffs']).dt.total_seconds() / 60

    # For the first occurrence of each Location, set Time_to_Next to the difference between it and the last occurrence, plus 7 days
    for loc in all_events['Location'].unique():
        loc_events = all_events[all_events['Location'] == loc]
        first_idx = loc_events.index[0]
        last_idx = loc_events.index[-1]
        _first_event_dt = all_events.loc[first_idx, 'Event_dt'] + \
            all_events.loc[first_idx, 'Day_timedelta']
        _last_event_dt = all_events.loc[last_idx, 'Event_dt'] + \
            all_events.loc[last_idx, 'Day_timedelta']
        # Calculate the time difference in minutes
        _time_diff = (_first_event_dt - _last_event_dt +
                      pd.Timedelta(days=7)).total_seconds() / 60
        all_events.loc[first_idx, 'Time from Previous'] = _time_diff
        time_diff = _time_diff
        all_events.loc[first_idx, 'Time from Previous'] = time_diff

    # Drop helper columns if not needed
    all_events.drop(['Day_timedelta', 'Event_dt', 'day_diffs',
                    'time_diffs'], axis=1, inplace=True)

    return all_events[['Location', 'Event Type', 'Day', 'Event Time', 'Time from Previous']]


def initialise_logistics_graph(all_events: pd.DataFrame,) -> nx.DiGraph:
    """
    Initialise the logistics graph with all events in a networkx directed graph.

    This function assumes that all_events is already sorted by Location, Day, and Event Time.
    Connects events based on the 'Location'.
    Node names are strings of the form "Location-Event Type-Day-Event Time".
    As events are already sorted, the edges are created to the next event in the same location.
    The edges are directed from the earlier event to the later event.
    The edge weights are the 'Time from Previous' values.
    This function returns a directed graph with nodes and edges representing the logistics events.
    All nodes are added with their attributes (i.e., Location, Event Type, Day, Event Time), and edges are added with weights.
    The very last event for each location is connected to the very first event for that location to create a cycle.

    Parameters:
        all_events (pd.DataFrame): DataFrame containing all events with columns ['Location', 'Event Type', 'Day', 'Event Time', 'Time from Previous'].
    Returns:
        nx.DiGraph: A directed graph with nodes and edges representing the logistics events.
    """
    G = nx.DiGraph()

    # Add nodes with attributes
    for _, row in all_events.iterrows():
        node_name = f'{row["Location"]}-{row["Event Type"]}-{row["Day"]}-{row["Event Time"]}'
        G.add_node(node_name, **row.to_dict())

    # Add edges based on 'Location' and 'Time from Previous'
    for i in range(len(all_events) - 1):
        if all_events.iloc[i]['Location'] == all_events.iloc[i + 1]['Location']:
            u = f'{all_events.iloc[i]["Location"]}-{all_events.iloc[i]["Event Type"]}-{all_events.iloc[i]["Day"]}-{all_events.iloc[i]["Event Time"]}'
            v = f'{all_events.iloc[i + 1]["Location"]}-{all_events.iloc[i + 1]["Event Type"]}-{all_events.iloc[i + 1]["Day"]}-{all_events.iloc[i + 1]["Event Time"]}'
            weight = all_events.iloc[i + 1]['Time from Previous']
            G.add_edge(u, v, weight=weight)

    # Connect the last event of each location to the first event of that location
    for loc in all_events['Location'].unique():
        last_event = all_events[all_events['Location'] == loc].iloc[-1]
        first_event = all_events[all_events['Location'] == loc].iloc[0]
        u = f'{last_event["Location"]}-{last_event["Event Type"]}-{last_event["Day"]}-{last_event["Event Time"]}'
        v = f'{first_event["Location"]}-{first_event["Event Type"]}-{first_event["Day"]}-{first_event["Event Time"]}'
        weight = first_event['Time from Previous']
        G.add_edge(u, v, weight=weight)

    return G


def connect_logistics_graph(G: nx.DiGraph, timetable_df: pd.DataFrame,) -> nx.DiGraph:
    """
    Connect the logistics graph with edges based on the timetable data.

    This function connects nodes in the graph based on the 'From' and 'To' columns in the timetable_df.
    It creates directed edges between nodes representing departure and arrival events.

    Node names are strings of the form "Location-Event Type-Day-Event Time".
    Departure nodes can be looked up by f'{From}-Departure-{Day}-{Depart_time}', and arrival nodes by f'{To}-Arrival-{Day}-{Arrive_time}'.
    The edges are directed from the departure node to the arrival node.
    The edge weights are from the 'Duration_minutes' column in the timetable_df.

    Parameters:
        G (nx.DiGraph): The directed graph to be connected.
        timetable_df (pd.DataFrame): DataFrame containing the timetable data with columns ['From', 'To', 'Depart_time', 'Arrive_time', 'Day'].

    Returns:
        nx.DiGraph: The updated directed graph with additional edges based on the timetable data.
    """
    for _, row in timetable_df.iterrows():
        # Create node names for departure and arrival
        from_node = f"{row['From']}-Departure-{row['Day']}-{row['Depart_time']}"
        to_node = f"{row['To']}-Arrival-{row['Day Arrival']}-{row['Arrive_time']}"
        # to_node = f"{row['To']}-Arrival-{row['Day']}-{row['Arrive_time']}"
        if G.has_node(from_node) and G.has_node(to_node):
            weight = row.get('Duration_minutes')
            G.add_edge(from_node, to_node, weight=weight)
        else:
            raise ValueError("One or both of the nodes do not exist in the graph:" +
                             f" {from_node}: {G.has_node(from_node)}, " +
                             f"{to_node}: {G.has_node(to_node)}")

    return G


def plot_time_expanded_logistics_graph(
    all_nodes_list: list[str],
    logistics_graph: nx.DiGraph,
    manual_order_locations: list[str],
    day_order: list[str],
    event_colors: dict = None,
    figsize=(20, 10),
    dpi=400
):
    """
    Plots a time-expanded logistics graph with manual location order and event type coloring.

    Assumes node names are strings of the form "Location-Event Type-Day-Event Time".
    This function plots the nodes in the graph with their respective colors based on the event type.

    Parameters
    ----------
    all_nodes_list : list
        List of node names (str) in the graph.
    logistics_graph : networkx.Graph or DiGraph
        The logistics graph object.
    manual_order_locations : list
        List of locations in the desired y-axis order.
    day_order : list
        List of days in the desired order.
    event_colors : dict, optional
        Mapping of event types to colors.
    figsize : tuple, optional
        Figure size.
    dpi : int, optional
        Figure DPI.
    """
    if event_colors is None:
        event_colors = {'Blood Matching': 'orange',
                        'Arrival': 'green', 'Departure': 'blue'}

    location_to_y_manual = {loc: i for i,
                            loc in enumerate(manual_order_locations)}
    node_pos_manual = {}
    for node in all_nodes_list:
        parts = node.split('-')
        loc = parts[0]
        n_type = parts[1]
        day = parts[2]
        time_str = parts[3]
        day_idx = day_order.index(day)
        dt = datetime(1900, 1, 1 + day_idx,
                      int(time_str[:2]), int(time_str[3:5]), int(time_str[6:]))
        node_pos_manual[node] = (mdates.date2num(
            dt), location_to_y_manual[loc], event_colors[n_type])

    plt.figure(figsize=figsize, dpi=dpi)

    # Draw nodes
    for node, (x, y, c) in node_pos_manual.items():
        plt.scatter(x, y, color=c, s=65)

    # Draw edges
    for u, v in logistics_graph.edges:
        if 'Sunday' in u and 'Monday' in v:
            continue
        x1, y1, _ = node_pos_manual[u]
        x2, y2, _ = node_pos_manual[v]
        plt.plot([x1, x2], [y1, y2], color='gray', alpha=0.3)

    plt.yticks(range(len(manual_order_locations)), manual_order_locations)
    plt.xlabel("Time (Day + HH:MM)")
    plt.title("Time-Expanded Logistics Graph")

    locator = mdates.AutoDateLocator()
    formatter = mdates.DateFormatter('%a %H:%M')
    plt.gca().xaxis.set_major_locator(locator)
    plt.gca().xaxis.set_major_formatter(formatter)

    # Add legend for event types
    legend_patches = [
        plt.Line2D([0], [0], marker='o', color='w', label='Blood Matching',
                   markerfacecolor=event_colors['Blood Matching'], markersize=15),
        plt.Line2D([0], [0], marker='o', color='w', label='Departure',
                   markerfacecolor=event_colors['Departure'], markersize=15),
        plt.Line2D([0], [0], marker='o', color='w', label='Arrival',
                   markerfacecolor=event_colors['Arrival'], markersize=15)
    ]
    plt.legend(handles=legend_patches, loc='upper center',
               bbox_to_anchor=(0.5, -0.12), ncol=3, frameon=False)
    plt.tight_layout()
    plt.show()


def save_logistics_graph(logistics_graph: nx.DiGraph, file_path: str):
    """
    Save the logistics graph to a file in either GraphML format or JSON/YAML format.

    Parameters
    ----------
    logistics_graph : networkx.Graph or DiGraph
        The logistics graph to be saved.
    file_path : str
        The path to the output file (should end with .graphml, .json, .yaml, or .yml).
    """
    if not file_path.endswith(('.graphml', '.json', '.yaml', '.yml')):
        raise ValueError("File path must end with .graphml, .json, .yaml, or .yml")
    try:
        if file_path.endswith('.graphml'):
            nx.write_graphml(logistics_graph, file_path)
        else:
            data = nx.node_link_data(logistics_graph)
            with open(file_path, 'w') as f:
                if file_path.endswith(('.yaml', '.yml')):
                    yaml.dump(data, f, sort_keys=False, Dumper=yaml.SafeDumper)
                else:
                    json.dump(data, f)
        print(f"Logistics graph saved successfully to {file_path}")
    except Exception as e:
        raise IOError(f"An error occurred while saving the graph: {e}")


def plot_simplified_location_graph(logistics_graph, figsize=(10, 8), node_size=800, arrowsize=20, font_size=12):
    """
    Plots a simplified logistics location graph, showing only connections between locations.

    Assumes node names are strings of the form "Location-Event Type-Day-Event Time".

    Parameters
    ----------
    logistics_graph : networkx.Graph or DiGraph
        The time-expanded logistics graph with nodes named as 'Location-EventType-Day-Time'.
    figsize : tuple, optional
        Size of the matplotlib figure.
    node_size : int, optional
        Size of the nodes in the plot.
    arrowsize : int, optional
        Size of the arrows in the plot.
    font_size : int, optional
        Font size for node labels.
    """
    # Extract unique locations from nodes
    locations = set()
    for node in logistics_graph.nodes:
        loc = node.split('-')[0]
        locations.add(loc)
    locations = sorted(locations)

    # Build a location-level graph (aggregate edges between locations)
    location_graph = nx.DiGraph()
    location_graph.add_nodes_from(locations)

    for u, v in logistics_graph.edges:
        loc_u = u.split('-')[0]
        loc_v = v.split('-')[0]
        if loc_u != loc_v:
            location_graph.add_edge(loc_u, loc_v)

    plt.figure(figsize=figsize)
    pos = nx.spring_layout(location_graph, seed=42)
    nx.draw(location_graph, pos, with_labels=True, node_size=node_size, node_color='skyblue',
            arrowsize=arrowsize, font_size=font_size)
    plt.title("Simplified Logistics Location Graph")
    plt.show()


def shortest_time_to_next_blood_matching(
    logistics_graph: nx.DiGraph,
    source_location: str,
    source_day: str,
    manual_order_locations: list[str],
    day_order: list[str],
    event_type: str = "Blood Matching",
    event_time: str = "08:00:00"
) -> pd.Series:
    """
    For a given source location and day, find the shortest time (in days, rounded up)
    to the next Blood Matching event at each other location.

    Parameters
    ----------
    logistics_graph : nx.DiGraph
        The time-expanded logistics graph.
    source_location : str
        The starting location (e.g., 'Colindale').
    source_day : str
        The starting day (e.g., 'Monday').
    manual_order_locations : list of str
        List of all locations.
    day_order : list of str
        List of days in order.
    event_type : str, optional
        The event type for the source node (default 'Blood Matching').
    event_time : str, optional
        The event time for the source node (default '08:00:00').

    Returns
    -------
    pd.Series
        Index: destination locations. Values: minimum time in days (rounded up) to reach the next Blood Matching event at that location.
    """

    source_node = f"{source_location}-{event_type}-{source_day}-{event_time}"
    results = {}

    for dst_location in manual_order_locations:
        # Find the Blood Matching event node at the destination location for each day
        min_minutes = np.inf
        for dst_day in day_order:
            dst_node = f"{dst_location}-Blood Matching-{dst_day}-{event_time}"
            try:
                # Shortest path from source_node to dst_node
                length = nx.shortest_path_length(logistics_graph, source_node, dst_node, weight='weight')
                if length < min_minutes:
                    min_minutes = length
            except (nx.NetworkXNoPath, nx.NodeNotFound):
                continue
        if dst_location == source_location:
            results[dst_location] = 0
        elif min_minutes < np.inf:
            results[dst_location] = int(np.ceil(min_minutes / (24 * 60)))
        else:
            results[dst_location] = np.nan

    return pd.Series(results, name=f"Shortest days from {source_location} ({source_day})")


def all_shortest_times_to_next_blood_matching(
    logistics_graph: nx.DiGraph,
    locations: list[str],
    day_order: list[str],
    event_type: str = "Blood Matching",
    event_time: str = "08:00:00"
) -> dict[str, pd.DataFrame]:
    """
    For all starting locations and all days, compute the shortest time (in days, rounded up)
    to the next Blood Matching event at every other location and day.

    Returns a dictionary mapping each day to a DataFrame (rows: source locations, columns: destination locations).

    Parameters
    ----------
    logistics_graph : nx.DiGraph
        The time-expanded logistics graph.
    locations : list of str
        List of all locations.
    day_order : list of str
        List of days in order.
    event_type : str, optional
        The event type for the source node (default 'Blood Matching').
    event_time : str, optional
        The event time for the source node (default '08:00:00').

    Returns
    -------
    dict[str, pd.DataFrame]
        Dictionary mapping day names to DataFrames (source x destination) of travel times in days.
    """

    # Precompute all Blood Matching nodes for each location and day
    blood_matching_nodes = {
        day: {
            loc: f"{loc}-{event_type}-{day}-{event_time}"
            for loc in locations
        }
        for day in day_order
    }

    # Prepare output: one DataFrame per day
    results = {day: pd.DataFrame(index=locations, columns=locations, dtype=float)
               for day in day_order}

    # For each source location and day, compute shortest paths to all nodes
    for src_day in day_order:
        for src_loc in locations:
            src_node = blood_matching_nodes[src_day][src_loc]
            # Compute shortest path lengths from this source node to all nodes
            try:
                lengths = nx.single_source_dijkstra_path_length(logistics_graph, src_node, weight='weight')
            except (nx.NetworkXNoPath, nx.NodeNotFound):
                lengths = {}
            # For each destination location, find the minimum time to any Blood Matching event at that location (any day)
            for dst_loc in locations:
                min_minutes = np.inf
                for dst_day in day_order:
                    dst_node = blood_matching_nodes[dst_day][dst_loc]
                    if dst_node in lengths:
                        if lengths[dst_node] < min_minutes:
                            min_minutes = lengths[dst_node]
                if src_loc == dst_loc:
                    results[src_day].loc[src_loc, dst_loc] = 0
                elif min_minutes < np.inf:
                    results[src_day].loc[src_loc, dst_loc] = int(np.ceil(min_minutes / (24 * 60)))
                else:
                    results[src_day].loc[src_loc, dst_loc] = np.nan

    return results


def save_shortest_times_to_file(
    shortest_times: dict[str, pd.DataFrame],
    output_file: str,
):
    """
    Save the shortest times DataFrames to file in either: Excel, TSV, or HDF5 format.
    
    Parameters
    ----------
    shortest_times : dict[str, pd.DataFrame]
        Dictionary mapping day names to DataFrames (source x destination) of travel times in days.
    output_file : str
        Path to the output file.
    """
    if output_file.endswith('.xlsx'):
        with pd.ExcelWriter(output_file) as writer:
            for day, df in shortest_times.items():
                df.to_excel(writer, sheet_name=day, index=True)
    elif output_file.endswith('.tsv'):
        for day, df in shortest_times.items():
            df.to_csv(f"{output_file}_{day}.tsv", sep='\t', index=True)
    elif output_file.endswith('.h5') or output_file.endswith('.hdf5'):
        with pd.HDFStore(output_file) as store:
            for day, df in shortest_times.items():
                store.put(day, df, format='table', data_columns=True)
    else:
        raise ValueError("Unsupported file format. Use .xlsx, .tsv, or .h5/.hdf5.")


def load_shortest_times_from_file(
    input_file: str,
    days_to_load: list[str|int] = None,) -> dict[str, pd.DataFrame]:
    """
    Load the shortest times DataFrames from file in either: Excel, TSV, or HDF5 format.
    
    Parameters
    ----------
    input_file : str
        Path to the input file.
    days_to_load : list[str|int], optional
        List of days to load from the file. If None, all days are loaded. Expected to be in the format of day names or indices.
    Returns
    -------
    dict[str, pd.DataFrame]
        Dictionary mapping day names to DataFrames (source x destination) of travel times in days.
    """
    if not os.path.exists(input_file):
        raise FileNotFoundError(f"The file {input_file} does not exist.")
    
    days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']

    if input_file.endswith('.xlsx'):
        df_dict = pd.read_excel(input_file, sheet_name=None)
        if days_to_load is None:
            return df_dict
        else:
            # Convert day names to string format if they are integers
            days_to_load = [days[day] if isinstance(day, int) else day for day in days_to_load]
            # Filter the dictionary to only include requested days
            return {day: df_dict[day] for day in days_to_load if day in df_dict}
    elif input_file.endswith('.tsv'):
        if days_to_load is None:
            return {f"Day_{i}": pd.read_csv(f"{input_file}_Day_{i}.tsv", sep='\t', index_col=0) for i in range(7)}
        else:
            # Convert day names to string format if they are integers
            days_to_load = [days[day] if isinstance(day, int) else day for day in days_to_load]
            return {day: pd.read_csv(f"{input_file}_{day}.tsv", sep='\t', index_col=0) for day in days_to_load}
    elif input_file.endswith('.h5') or input_file.endswith('.hdf5'):
        with pd.HDFStore(input_file) as store:
            if days_to_load is None:
                return {key: store[key] for key in store.keys()}
            else:
                # Convert day names to string format if they are integers
                days_to_load = [days[day] if isinstance(day, int) else day for day in days_to_load]
                return {day: store[day] for day in days_to_load if day in store.keys()}
    else:
        raise ValueError("Unsupported file format. Use .xlsx, .tsv, or .h5/.hdf5.")  


def plot_blood_flows(df, custom_title="Average Weekly Flow"):
    # Approximate coordinates from your image
    pos = {
        'Newcastle': (5, 10), 'Lancaster': (3, 8), 'Manchester': (4, 7), 
        'Liverpool': (3, 7), 'Barnsley': (5, 7.2), 'Birmingham': (4.5, 5),
        'Filton': (3.5, 3), 'Oxford': (5, 3.5), 'Southampton': (5, 2),
        'Plymouth': (1, 1), 'Cambridge': (7, 4.5), 'Colindale': (6.5, 3.5),
        'Tooting': (6.8, 3), 'Basildon': (7.5, 3.5)
    }
    
    # Aggregate time-expanded nodes into pure Location -> Location flows
    geo_df = df.groupby(['Origin', 'Destination'])['Mean_Weekly_Units'].sum().reset_index()
    
    G = nx.DiGraph()
    for _, row in geo_df.iterrows():
        G.add_edge(row['Origin'], row['Destination'], weight=row['Mean_Weekly_Units'])

    plt.figure(figsize=(12, 9))
    
    # Draw nodes and labels
    nx.draw_networkx_nodes(G, pos, node_size=500, node_color='darkred', alpha=0.8)
    nx.draw_networkx_labels(G, pos, font_size=9, font_weight='bold')

    # Draw edges with varying thickness
    weights = [G[u][v]['weight'] for u, v in G.edges()]
    max_weight = max(weights) if weights else 1
    # Scale: busiest route is 10px thick
    widths = [(w / max_weight) * 10 for w in weights]
    
    nx.draw_networkx_edges(G, pos, width=widths, edge_color='black', 
                           alpha=0.5, arrowsize=20, connectionstyle="arc3,rad=0.1")
    
    plt.title(custom_title)
    plt.axis('off')
    plt.show()


def analyze_scenario_statistics(
    files_dict, 
    logistics_graph, 
    id_to_name, 
    day_order, 
    warm_up=42, 
    horizon=42,
    date_col=0, 
    src_col=1, 
    dst_col=2, 
    unit_col=3,
    pat_grp_col=None,
    move_reason=None,
    disaggregate=False  # New flag for Day/Time breakdown
):
    """
    Processes .npz scenarios. 
    If disaggregate=True: Results are broken down by specific departure day/time.
    If disaggregate=False: Results are aggregated by Origin-Destination location pair.
    """
    
    # 1. Internal Path Cache
    def _build_cache():
        cache = {}
        locations = list(id_to_name.values())
        for src_day in day_order:
            for src_loc in locations:
                src_node = f"{src_loc}-Blood Matching-{src_day}-08:00:00"
                try:
                    paths = nx.single_source_dijkstra_path(logistics_graph, src_node, weight='weight')
                    lengths = nx.single_source_dijkstra_path_length(logistics_graph, src_node, weight='weight')
                    for dst_loc in locations:
                        if src_loc == dst_loc: continue
                        target, min_d = None, float('inf')
                        for d_day in day_order:
                            d_node = f"{dst_loc}-Blood Matching-{d_day}-08:00:00"
                            if d_node in lengths and lengths[d_node] < min_d:
                                min_d, target = lengths[d_node], d_node
                        cache[(src_loc, dst_loc, src_day)] = paths.get(target)
                except: continue
        return cache

    path_cache = _build_cache()
    scenario_results = {}
    weeks_in_horizon = (horizon - warm_up) / 7

    for s_name, f_path in tqdm.tqdm(files_dict.items(), desc="Processing Scenarios", position=0,):
        if f_path.endswith('_output.tsv'):
            f_path = f_path.replace('_output.tsv', '_moves.npz')
        
        if not os.path.exists(f_path): continue

        data = np.load(f_path)
        replications = data.files
        num_reps = len(replications)
        
        # Key: (u, v) edge -> Value: np.array of size num_reps
        rep_data = {} 

        for idx, rep_key in tqdm.tqdm(enumerate(replications), desc="Processing Replications", position=1,
                                      leave=False, total=num_reps,):
            moves = data[rep_key]
            mask = (moves[:, date_col] > warm_up) & (moves[:, date_col] <= (horizon))
            ss_moves = moves[mask]
            
            if type(pat_grp_col) == int and type(move_reason) == int:
                ss_moves = ss_moves[ss_moves[:, pat_grp_col] == move_reason]

            for row in ss_moves:
                day_val, s_id, d_id = int(row[date_col]), int(row[src_col]), int(row[dst_col])
                day_name = day_order[(day_val - 1) % 7]
                src_name, dst_name = id_to_name[s_id], id_to_name[d_id]
                
                path = path_cache.get((src_name, dst_name, day_name))
                if path:
                    for i in range(len(path) - 1):
                        edge = (path[i], path[i+1])
                        u_loc, v_loc = edge[0].split('-')[0], edge[1].split('-')[0]
                        
                        if u_loc != v_loc: # Transport leg check
                            if edge not in rep_data:
                                rep_data[edge] = np.zeros(num_reps)
                            rep_data[edge][idx] += 1

        # 2. Aggregation Logic
        temp_list = []
        for (u, v), totals_array in rep_data.items():
            # Parse node strings: "Location-Type-Day-Time"
            u_parts = u.split('-')
            v_parts = v.split('-')
            
            temp_list.append({
                'Origin': u_parts[0],
                'Destination': v_parts[0],
                'Dep_Day': u_parts[2],
                'Dep_Time': u_parts[3],
                'Weekly_Averages': totals_array / weeks_in_horizon
            })

        df_raw = pd.DataFrame(temp_list)
        
        if disaggregate:
            # Group by specific time-expanded edge
            group_cols = ['Origin', 'Destination', 'Dep_Day', 'Dep_Time']
        else:
            # Group by physical route only
            group_cols = ['Origin', 'Destination']

        # Custom aggregation to handle the numpy arrays correctly
        final_rows = []
        for name, group in df_raw.groupby(group_cols):
            # Sum the weekly averages across all trips in that group (for all reps)
            combined_reps = np.sum(np.stack(group['Weekly_Averages'].values), axis=0)
            
            row = {
                'Origin': name[0] if disaggregate else name[0],
                'Destination': name[1] if disaggregate else name[1],
                'Mean_Weekly_Units': np.mean(combined_reps),
                'Std_Error': stats.sem(combined_reps),
                'n_reps': num_reps,
                'Std_Dev': np.std(combined_reps,),
            }
            if disaggregate:
                row['Dep_Day'] = name[2]
                row['Dep_Time'] = name[3]
            
            final_rows.append(row)

        scenario_results[s_name] = pd.DataFrame(final_rows).sort_values('Mean_Weekly_Units', ascending=False)
        data.close()

    return scenario_results


def aggregate_disaggregated_results(df, level='route'):
    """
    Aggregates disaggregated leg data while properly propagating Mean, 
    Standard Error (SEM), and Standard Deviation (SD).
    
    Parameters
    ----------
    df : pd.DataFrame
        The disaggregated DataFrame (output from analyze_scenario_statistics).
        Expected columns: ['Mean_Weekly_Units', 'Std_Error', 'Std_Dev', 'n_reps']
    level : str, optional ('route' or 'day')
        'route': Aggregates everything to Origin -> Destination.
        'day': Aggregates to Origin -> Destination -> Day.
        
    Returns
    -------
    pd.DataFrame
        Aggregated results with properly propagated statistics.
    """
    if 'Dep_Day' not in df.columns and 'Dep_Time' not in df.columns:
        print("DataFrame is already aggregated. No disaggregated columns found.")
        return df
    
    if level == 'day':
        group_cols = ['Origin', 'Destination', 'Dep_Day']
    elif level == 'route':
        group_cols = ['Origin', 'Destination']
    else:
        raise ValueError("Level must be 'day' or 'route'")

    # Error Propagation Logic:
    # 1. Sum of Means: μ_total = Σ μ_i
    # 2. Sum of Variances (for SD and SEM): σ_total = sqrt(Σ σ_i^2)
    def propagate_error(x):
        return np.sqrt(np.sum(np.square(x)))

    agg_funcs = {
        'Mean_Weekly_Units': 'sum',
        'Std_Error': propagate_error,
        'Std_Dev': propagate_error,
        'n_reps': 'first' # Sample size (replications) remains constant
    }

    # Tracking how many trips are being collapsed into this one row
    df = df.copy()
    df['Trips_Count'] = 1
    agg_funcs['Trips_Count'] = 'sum'

    aggregated_df = df.groupby(group_cols).agg(agg_funcs).reset_index()
    
    return aggregated_df.sort_values('Mean_Weekly_Units', ascending=False)


def plot_scenario_comparison(
    df_test, 
    df_bench, 
    pos=None,
    text_pos=None, 
    max_diff=None, # Crucial for cross-plot comparison
    metric_for_alpha='SEM', 
    pos_color='#e66101', 
    neg_color='#5e3c99',
    figsize=(12, 9), 
    dpi=300, 
    save_path=None,
    z_threshold=2.0,
    width_multiplier=1.0,
):
    """
    Plots differences between two scenarios. Use 'max_diff' to ensure 
    visual consistency across multiple plots (e.g., E02 vs L01 and E03 vs L01).
    """
    rng = np.random.default_rng(seed=42)  # For reproducibility

    if pos is None:
        pos = {
            'Newcastle': (6, 9), 'Lancaster': (3, 8), 'Manchester': (4, 7), 
            'Liverpool': (3, 7), 'Barnsley': (5.5, 7.2), 'Birmingham': (4.5, 5),
            'Filton': (3.5, 3), 'Oxford': (5, 3.5), 'Southampton': (5, 2),
            'Plymouth': (2.4, 1.85), 'Cambridge': (7, 4.5), 'Colindale': (5.7, 3.8),
            'Tooting': (6.8, 2.5), 'Basildon': (7.5, 3.5)
        }
        if text_pos is None:
            text_pos = {
                'Newcastle': (6, 9.15), 'Lancaster': (3, 8.15), 'Manchester': (4, 7.3),
                'Liverpool': (2.8, 7.1), 'Barnsley': (5.5, 7.35), 'Birmingham': (5, 5.15),
                'Filton': (3.2, 3.15), 'Oxford': (5.25, 3.), 'Southampton': (5, 1.5),
                'Plymouth': (2.4, 1.4), 'Cambridge': (7, 4.65), 'Colindale': (5.8, 4.2),
                'Tooting': (6.8, 2.), 'Basildon': (7.5, 3.),
            }

    # 1. Merge and calculate differences
    merged = pd.merge(df_test, df_bench, on=['Origin', 'Destination'], 
                      how='outer', suffixes=('_t', '_b')).fillna(0)
    
    merged['diff_mean'] = merged['Mean_Weekly_Units_t'] - merged['Mean_Weekly_Units_b']
    merged['diff_sem'] = np.sqrt(merged['Std_Error_t']**2 + merged['Std_Error_b']**2)
    merged['diff_sd'] = np.sqrt(merged['Std_Dev_t']**2 + merged['Std_Dev_b']**2)

    # If no global max_diff is provided, calculate from local data
    if max_diff is None:
        max_diff = merged['diff_mean'].abs().max() if not merged.empty else 1
    # Avoid divide-by-zero in linewidth scaling when all differences are zero.
    if max_diff <= 0:
        max_diff = 1

    def _line_width_from_diff(diff_value):
        rel_size = abs(diff_value) / max_diff
        return (rel_size * 12 + 0.5) * width_multiplier

    fig, ax = plt.subplots(figsize=figsize, dpi=dpi)
    
    # 2. Draw Nodes (Clean, white background to avoid clashing with Seaborn/Text)
    for loc, p in pos.items():
        ax.scatter(p[0], p[1], s=100, c='white', edgecolors='#333333', lw=0.8, zorder=10)
        if text_pos is None:
            ax.text(p[0], p[1]+0.15, loc, zorder=11, ha='center', va='bottom')
        else:
            ax.text(text_pos.get(loc, p)[0], text_pos.get(loc, p)[1], loc, zorder=11, ha='center', va='bottom')

    # 3. Draw Edges
    for _, row in merged.iterrows():
        if abs(row['diff_mean']) < 0.05: continue # Ignore trace differences
        
        u_p, v_p = np.array(pos[row['Origin']]), np.array(pos[row['Destination']])
        color = pos_color if row['diff_mean'] > 0 else neg_color
        
        # Line width is now anchored to the provided global max_diff
        # width = (abs(row['diff_mean']) / max_diff) * 10 + 0.5
        lw = _line_width_from_diff(row['diff_mean'])
        
        # Alpha/Transparency Logic
        if metric_for_alpha == 'SEM':
            z = abs(row['diff_mean']) / (row['diff_sem'] + 1e-9)
            alpha = np.clip(z / z_threshold, 0.1, 0.8)
        elif metric_for_alpha == 'STDEV':
            z = abs(row['diff_mean']) / (row['diff_sd'] + 1e-9)
            alpha = np.clip(z / z_threshold, 0.1, 0.8)
        else:
            alpha = 0.75

        # Connection style for bi-directional visibility
        # Curved arcs prevent 'London blob' overlap
        arc_rad = 0.2
        
        # Draw the main flow line (no arrow head)
        ax.annotate("", xy=v_p, xytext=u_p,
                    arrowprops=dict(arrowstyle="-", color=color, lw=lw, alpha=alpha,
                                    connectionstyle=f"arc3,rad={arc_rad}",
                                    shrinkA=8, shrinkB=8))

        # Draw a tiny segment in the middle with the arrowhead
        shrinkA_jitter = 25 * (0.6 + rng.random()/2)
        shrinkB_jitter = 40 * (0.8 + rng.random()/3)
        mid_arrow = FancyArrowPatch(
            u_p, v_p, 
            connectionstyle=f"arc3,rad={arc_rad}",
            arrowstyle='-|>,head_length=8,head_width=13',
            # arrowstyle='-|>',
            color=color,  # Black arrowhead for contrast
            lw=0.0,  # No line, just the arrowhead
            alpha=1,
            # mutation_scale=m_scale, 
            shrinkA=shrinkA_jitter, shrinkB=shrinkB_jitter  # No shrink so it stays in the middle
        )
        ax.add_patch(mid_arrow)

    # Thickness legend values include the current max_diff by construction.
    legend_diffs = [20, 100, 200, 400, 800]
    legend_handles = [
        Line2D([0], [0], color='#444444', lw=_line_width_from_diff(diff_val), alpha=0.9)
        for diff_val in legend_diffs
    ]
    legend_labels = [
        f" {diff_val:.0f}"
        for diff_val in legend_diffs
    ]
    ax.legend(
        legend_handles,
        legend_labels,
        title="Δ Mean weekly units",
        loc='upper left',
        bbox_to_anchor=(0.67, 0.88),
        frameon=True,
        framealpha=0.95,
        facecolor='white',
        edgecolor='#bfbfbf',
        fontsize=12,
        title_fontsize=15,
    )

    ax.set_axis_off()
    
    if save_path:
        plt.savefig(save_path, format='pdf', bbox_inches='tight', dpi=dpi)
    
    plt.show()
    return max_diff # Return it so you can use it for the next plot
